'use client'

import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('english')

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('riva-language')
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('riva-language', newLanguage)
  }

  const translations = {
    english: {
      // Navbar
      home: 'Home',
      about: 'About',
      features: 'Features',
      howItWorksNav: 'How It Works',
      appNav: 'App',
      pricing: 'Pricing',
      contact: 'Contact',
      login: 'Login',
      register: 'Register',
      // Hero
      heroTitle: 'Smarter Vehicles.',
      heroSubtitle: 'Safer Roads.',
      heroDescription: 'RIVA is the next-generation intelligent vehicle assistant that prevents accidents, detects risks, and optimizes fleet performance in real-time.',
      getStarted: 'Get Started',
      downloadApp: 'Download App',
      trustedBy: 'Trusted by 10,000+ Drivers',
      // Features
      aiPowered: 'AI-Powered Vehicle Intelligence',
      // Download App Page
      aboutThisApp: 'About this app',
      aboutThisAppDescription: 'RIVA is the next-generation intelligent vehicle assistant that prevents accidents, detects risks, and optimizes fleet performance in real-time. Our AI-powered system continuously monitors vehicle health, driver behavior, and environmental conditions to provide instant safety alerts and predictive maintenance recommendations.',
      dataSafety: 'Data safety',
      encryptedTransfer: 'Encrypted data transfer',
      encryptedTransferDesc: 'Your data is transferred securely',
      requestDeletion: 'You can request that data be deleted',
      requestDeletionDesc: 'Send deletion requests to the developer',
      whatsNew: "What's new",
      appFeatures: 'App Features',
      realtimeMonitoring: 'Real-time Monitoring',
      safetyAlerts: 'Safety Alerts',
      fleetManagement: 'Fleet Management',
      predictiveMaintenance: 'Predictive Maintenance',
      developerContact: 'Developer contact',
      email: 'Email',
      phone: 'Phone',
      website: 'Website',
      backToHome: 'Back to Home',
      install: 'Install',
      reviews: 'reviews',
      downloads: 'downloads',
      ratedFor: 'Rated for',
      updatedOn: 'Updated on',
      // Footer
      rightsReserved: 'All rights reserved',
      followUs: 'Follow Us',
      quickLinks: 'Quick Links',
      company: 'Company',
      // Features Section
      featuresTitle: 'Powerful Features',
      featuresSubtitle: 'Everything you need to manage your fleet efficiently',
      accidentPrevention: 'Accident Prevention',
      accidentPreventionDesc: 'AI-powered system detects and prevents accidents before they happen',
      fuelMonitoring: 'Fuel Monitoring',
      fuelMonitoringDesc: 'Real-time fuel tracking to prevent theft and optimize usage',
      gpsTracking: 'GPS Tracking',
      gpsTrackingDesc: '24/7 vehicle location monitoring and geofencing capabilities',
      // How It Works
      howItWorks: 'How It Works',
      howItWorksSubtitle: 'Simple steps to get started with RIVA',
      step1: 'Sign Up',
      step1Desc: 'Create your account in minutes',
      step2: 'Install App',
      step2Desc: 'Download and install the RIVA app',
      step3: 'Connect Vehicles',
      step3Desc: 'Add your vehicles to the system',
      step4: 'Start Monitoring',
      step4Desc: 'Begin real-time monitoring and safety alerts',
      // Features Component
      coreFeatures: 'Core Features',
      everythingYouNeed: 'Everything You Need for Smart Mobility',
      alcoholDetection: 'Alcohol Detection',
      alcoholDetectionDesc: 'Real-time BAC analysis & engine lock system',
      fuelMonitoring: 'Fuel Monitoring',
      fuelMonitoringDesc: 'Detect theft and unusual consumption',
      gpsTracking: 'GPS Tracking',
      gpsTrackingDesc: 'Live location & route monitoring',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Voice assistant in Kinyarwanda',
      kinyarwandaBadge: 'Kinyarwanda',
      fleetManagement: 'Fleet Management',
      fleetManagementDesc: 'Manage unlimited vehicles',
      // How It Works Component
      simpleSmartConnected: 'Simple. Smart. Connected.',
      installDevice: 'Install Device',
      installDeviceDesc: 'Plug RIVA into your vehicle',
      connectApp: 'Connect App',
      connectAppDesc: 'Pair with RIVA mobile app',
      monitorAI: 'Monitor AI',
      monitorAIDesc: 'Get real-time intelligence',
      // CTA Component
      readyToTransform: 'Ready to Transform Your Fleet?',
      joinThousands: 'Join thousands of drivers who trust RIVA for safer journeys',
      requestDemo: 'Request Demo',
      // App Preview Component
      mobileAppPreview: 'Mobile App Preview',
      viewAppScreens: 'View App Screens',
      realImpact: 'Real Impact, Real Results',
      fewerAccidents: 'Fewer Accidents',
      drunkDrivingPrevented: 'Drunk driving prevented',
      costSavings: 'Cost Savings',
      fuelTheftEliminated: 'Fuel theft eliminated',
      fleetEfficiency: 'Fleet Efficiency',
      vehiclesManaged: 'Vehicles managed',
      rivaAppScreens: 'RIVA App Screens',
      dashboard: 'Dashboard',
      realtimeVehicleStats: 'Real-time vehicle tracking',
      aiAssistant: 'AI Assistant',
      rivaSoulVoice: 'RIVA SOUL Voice',
      fuelMonitor: 'Fuel Monitor',
      fuelTracking: 'Fuel tracking',
      safetyAlerts: 'Safety Alerts',
      instantNotifications: 'Instant notifications',
      gpsTrackingApp: 'GPS Tracking',
      liveLocation: 'Live location',
      diagnostics: 'Diagnostics',
      vehicleHealth: 'Vehicle health',
      driverBehaviorAnalysis: 'Driver behavior analysis',
      fleetManagement: 'Fleet management dashboard',
      // Contact Page
      contactUs: 'Contact Us',
      contactDescription: 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
      sendMessage: 'Send us a message',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      subject: 'Subject',
      message: 'Message',
      sendButton: 'Send Message',
      findUsOnSocial: 'Find us on social media',
      socialDescription: 'Stay connected with us on social media for updates, news, and tips on road safety.',
      visitOurOffice: 'Visit Our Office',
      visitOfficeDesc: 'Come visit us at our headquarters in Kigali, Rwanda',
      howCanWeHelp: 'How can we help?',
      tellUsMore: 'Tell us more about your inquiry...',
      // About Page
      aboutRiva: 'About RIVA',
      aboutDescription: 'RIVA is a next-generation intelligent vehicle assistant that prevents accidents, detects risks, and optimizes fleet performance in real-time. We\'re on a mission to make roads safer for everyone.',
      ourStory: 'Our Story',
      storyParagraph1: 'RIVA was born from a simple but urgent problem: too many lives are lost on our roads due to preventable causes like drunk driving, poor vehicle monitoring, and lack of real-time data.',
      storyParagraph2: 'Starting in Rwanda, we saw the everyday challenges faced by drivers, fleet owners, and governments — from accidents caused by alcohol to fuel theft and inefficient fleet management.',
      storyParagraph3: 'We asked a bold question:',
      storyParagraph4: '"What if vehicles could think, detect risks, and protect lives in real time?"',
      storyParagraph5: 'That question led to RIVA — a Real-time Intelligence Vehicle Assistant powered by AI and IoT.',
      storyParagraph6: 'A system designed not just to monitor vehicles, but to actively prevent accidents, improve efficiency, and transform mobility across Rwanda and beyond.',
      ourMission: 'Our Mission',
      missionDescription: 'To make roads safer and transportation smarter by using AI-powered vehicle intelligence that detects risks, prevents accidents, and empowers drivers, fleet owners, and governments with real-time insights.',
      ourVision: 'Our Vision',
      visionDescription: 'To become the leading intelligent mobility platform in Rwanda and globally, where every vehicle is connected, every journey is safe, and every decision is powered by real-time data.',
      ourValues: 'Our Values',
      valuesDescription: 'The principles that guide everything we do',
      safetyFirst: 'Safety First',
      safetyFirstDesc: 'We prioritize safety above all else, ensuring every driver returns home safely.',
      aiInnovation: 'AI Innovation',
      aiInnovationDesc: 'Leveraging cutting-edge artificial intelligence to transform fleet management.',
      communityImpact: 'Community Impact',
      communityImpactDesc: 'Making roads safer for everyone, one vehicle at a time.',
      vehiclesProtected: 'Vehicles Protected',
      accuracyRate: 'Accuracy Rate',
      partnerCompanies: 'Partner Companies',
      monitoring: 'Monitoring',
      ourTechnology: 'Our Technology',
      technologyDescription: 'Cutting-edge AI that understands your vehicle',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Our proprietary AI system, RIVA SOUL, learns your vehicle\'s patterns and provides intelligent predictions. It supports multiple languages including Kinyarwanda, making it accessible to all drivers in Rwanda.',
      realtimeAlcoholDetection: 'Real-time alcohol detection',
      fuelTheftPrevention: 'Fuel theft prevention',
      predictiveMaintenance: 'Predictive maintenance',
      voiceAssistantKinyarwanda: 'Voice assistant in Kinyarwanda',
      smartMonitoring: 'Smart Monitoring',
      smartMonitoringDesc: 'RIVA leverages intelligent sensor technology embedded within the vehicle to capture real-time data on performance, behavior, and safety conditions. This data is processed by our AI engine to identify risks, optimize operations, and deliver proactive alerts before problems occur.',
      realtimeGpsTracking: 'Real-time GPS tracking & geofencing',
      intelligentFuelUsage: 'Intelligent fuel usage monitoring',
      sensorBasedDiagnostics: 'Sensor-based vehicle diagnostics',
      instantSafetyAlerts: 'Instant AI-powered safety alerts',
      ourTeam: 'Our Team',
      teamDescription: 'Passionate experts dedicated to road safety',
      // Try App Page
      demoMode: 'Demo Mode',
      tryRivaApp: 'Try RIVA App',
      tryRivaAppDesc: 'Experience RIVA using Expo Go - No installation required',
      installExpoGo: 'Install Expo Go',
      installExpoGoDesc: 'Download Expo Go from Play Store',
      openExpoGo: 'Open Expo Go',
      openExpoGoDesc: 'Launch the Expo Go app on your device',
      scanQrCode: 'Scan QR Code',
      scanQrCodeDesc: 'Scan the QR code below with Expo Go',
      startUsing: 'Start Using',
      startUsingDesc: 'Begin testing the RIVA app',
      scanQrCodeTitle: 'Scan QR Code',
      scanQrCodeInstruction: 'Use Expo Go to scan this QR code and launch the demo',
      qrCodePlaceholder: 'QR code will be displayed here from your Expo project',
      getExpoGo: 'Get Expo Go on Play Store',
      demoInformation: 'Demo Information',
      demoInfoDesc: 'This is a demo version of the RIVA app running on Expo Go. You can test the core features including real-time monitoring, AI-powered alerts, and fleet management without installing the full application. The demo provides a hands-on experience of our intelligent vehicle assistant technology.',
    },
    kinyarwanda: {
      // Navbar
      home: 'Ahabanza',
      about: 'Ibyerekeye',
      features: 'Ibikorwa',
      howItWorksNav: 'Ibikorwa',
      appNav: 'Porogaramu',
      pricing: 'Igiciro',
      contact: 'Twandikire',
      login: 'Injira',
      register: 'Iyandikishe',
      // Hero
      heroTitle: 'Modoka Zimwe.',
      heroSubtitle: 'Mihanda Amanzi.',
      heroDescription: 'RIVA ni umufasha wa modoka wihuse kuri mudasobwa ubu, wica imyitwarire, ikura ibyago, no guhindura imikorere yamasosiyete ya modoka mu gihe cyose.',
      getStarted: 'Tangira',
      downloadApp: 'Shyira Porogaramu',
      trustedBy: 'Abayobozi 10,000+ Bakoresha',
      // Features
      aiPowered: 'Ubufasha bwo Kuvuga Modoka bwo Mudasobwa',
      // Download App Page
      aboutThisApp: 'Ibyerekeye iyi porogaramu',
      aboutThisAppDescription: 'RIVA ni umufasha wa modoka wihuse kuri mudasobwa ubu, wica imyitwarire, ikura ibyago, no guhindura imikorere yamasosiyete ya modoka mu gihe cyose. Sisitemu yacu yihuse kuri mudasobwa ibuza ubuzima bwa modoka, imyitwarire yabayobozi, nimbibi zikora kugira ngo itanga ibyabujisha byubuzima nihuse nubushishozi bwo kubungabunga.',
      dataSafety: 'Guhisha amakuru',
      encryptedTransfer: 'Kohereza amakuru birindwa',
      encryptedTransferDesc: 'Amakuru yawe akoherwa mu buryo bwihuse',
      requestDeletion: 'Ugushoboza gusaba amakuru agasibwe',
      requestDeletionDesc: 'Ohereza ibyifuzo byo gusiba amakuru kwa muhanga',
      whatsNew: "Ibyo Bishya",
      appFeatures: 'Ibikorwa bya Porogaramu',
      realtimeMonitoring: 'Gusubira Igihe',
      safetyAlerts: 'Ibyabujisha Ubuzima',
      fleetManagement: 'Gucunga Imodoka',
      predictiveMaintenance: 'Gubungabunga',
      developerContact: 'Twandikire Muhanga',
      email: 'Imeli',
      phone: 'Telefone',
      website: 'Urubuga',
      backToHome: 'Subira kuri Ahabanza',
      install: 'Shyira',
      reviews: 'ibyishimo',
      downloads: 'iyoherejwe',
      ratedFor: 'Yemewe kuri',
      updatedOn: 'Yahinduwe ku',
      // Footer
      rightsReserved: 'Uburenganzira bwose burabitswe',
      followUs: 'Dutezere',
      quickLinks: 'Amabara yihuse',
      company: 'Kampuni',
      // Features Section
      featuresTitle: 'Ibikorwa Byihuse',
      featuresSubtitle: 'Byose ukeneye kugucunga imodoka yawe neza',
      accidentPrevention: 'Kwica Imyitwarire',
      accidentPreventionDesc: 'Sisitemu yihuse kuri mudasobwa ikura no guca imyitwarire mbere yuko biba',
      fuelMonitoring: 'Gusubira Amavuta',
      fuelMonitoringDesc: 'Gusubira amavuta mu gihe cyose kugira ngo ugahaze amavuta no gukoresha neza',
      gpsTracking: 'Gusubira GPS',
      gpsTrackingDesc: 'Gusubira aho imodoka ziri amasaha 24 kumunsi wose nubushobozi bwo gutwara',
      // How It Works
      howItWorks: 'Ibikorwa',
      howItWorksSubtitle: 'Intambwe zihuse kuri tangira na RIVA',
      step1: 'Iyandikishe',
      step1Desc: 'Yandikishe konti yawe mu iminota',
      step2: 'Shyira Porogaramu',
      step2Desc: 'Shyira na ushyire porogaramu ya RIVA',
      step3: 'Huzamo Imodoka',
      step3Desc: 'Ongera imodoka yawe muri sisitemu',
      step4: 'Tangira Gusubira',
      step4Desc: 'Tangira gusubira mu gihe cyose nibyabujisha byubuzima',
      // Features Component
      coreFeatures: 'Ibikorwa Byihuse',
      everythingYouNeed: 'Byose ukeneye kugucunga imodoka yawe neza',
      alcoholDetection: 'Kwica Uwohe',
      alcoholDetectionDesc: 'Gusubira BAC mu gihe cyose nuburyo bwo guhisha injini',
      fuelMonitoring: 'Gusubira Amavuta',
      fuelMonitoringDesc: 'Gusubira amavuta mu gihe cyose kugira ngo ugahaze amavuta no gukoresha neza',
      gpsTracking: 'Gusubira GPS',
      gpsTrackingDesc: 'Gusubira aho imodoka ziri amasaha 24 kumunsi wose nubushobozi bwo gutwara',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Umufasha wuvuga mu Kinyarwanda',
      kinyarwandaBadge: 'Kinyarwanda',
      fleetManagement: 'Gucunga Imodoka',
      fleetManagementDesc: 'Gucunga imodoka zingana',
      // How It Works Component
      simpleSmartConnected: 'Byihuse. Byihuse. Bihuza.',
      installDevice: 'Shyira Icyo',
      installDeviceDesc: 'Shyira RIVA muri imodoka yawe',
      connectApp: 'Huzamo Porogaramu',
      connectAppDesc: 'Huzamo na porogaramu ya RIVA ya telefone',
      monitorAI: 'Gusubira AI',
      monitorAIDesc: 'Wobikire ubumenyi mu gihe cyose',
      // CTA Component
      readyToTransform: 'Ufite guhindura imodoka zawe?',
      joinThousands: 'Yiyamamane nabayobozi ibihumbi bakoresha RIVA kugira ngo mihanda manzira',
      requestDemo: 'Saba Igaragazwa',
      // App Preview Component
      mobileAppPreview: 'Igaragaza rya Porogaramu ya Telefoni',
      viewAppScreens: 'Wibuke Amasikini ya Porogaramu',
      realImpact: 'Ingaruka Zikora, Ibisubizo Byikora',
      fewerAccidents: 'Imyitwarire Mirya',
      drunkDrivingPrevented: 'Uwohe wabujijwe',
      costSavings: 'Kuvana ingengo',
      fuelTheftEliminated: 'Guhaza amavuta byarahindutse',
      fleetEfficiency: 'Imikorere yamasosiyete',
      vehiclesManaged: 'Imodoka zirabitswe',
      rivaAppScreens: 'Amasikini ya Porogaramu ya RIVA',
      dashboard: 'Ikaze',
      realtimeVehicleStats: 'Gusubira imodoka mu gihe cyose',
      aiAssistant: 'Umufasha wihuse kuri mudasobwa',
      rivaSoulVoice: 'RIVA SOUL Ijwi',
      fuelMonitor: 'Gusubira Amavuta',
      fuelTracking: 'Gusubira amavuta',
      safetyAlerts: 'Ibyabujisha Ubuzima',
      instantNotifications: 'Ubutumwa bwihuse',
      gpsTrackingApp: 'Gusubira GPS',
      liveLocation: 'Aho imodoka ziri',
      diagnostics: 'Igerageza',
      vehicleHealth: 'Ubuzima bwa modoka',
      driverBehaviorAnalysis: 'Gusubira imyitwarire yabayobozi',
      fleetManagement: 'Ikaze ryamasosiyete ya modoka',
      // Contact Page
      contactUs: 'Twandikire',
      contactDescription: 'Ufite ibibazo? Dufite ko tubwire. Ohereza ubutumwa dutahinduka',
      sendMessage: 'Ohereza ubutumwa',
      fullName: 'Izina ryose',
      emailAddress: 'Aderesi ya Imeli',
      phoneNumber: 'Numero ya Telefoni',
      subject: 'Insanganyamatsiko',
      message: 'Ubutumwa',
      sendButton: 'Ohereza Ubutumwa',
      findUsOnSocial: 'Tuyisemo ku mbuga nkoranyambaga',
      socialDescription: 'Tuyisemo ku mbuga nkoranyambaga kugira ngo wamenye ibindi nubujisha bwo mu gihugu',
      visitOurOffice: 'Tuyisemo mu biro',
      visitOfficeDesc: 'Tuyisemo mu biro byacu i Kigali, Rwanda',
      howCanWeHelp: 'Tubwira ko twagufasha iki?',
      tellUsMore: 'Tubwire ibindi byo ufite...',
      // About Page
      aboutRiva: 'Ibyerekeye RIVA',
      aboutDescription: 'RIVA ni umufasha wa modoka wihuse kuri mudasobwa ubu, wica imyitwarire, ikura ibyago, no guhindura imikorere yamasosiyete ya modoka mu gihe cyose. Dufite intego zo gukora mihanda manzira kuri buri wese.',
      ourStory: 'Ibikorwa Byacu',
      storyParagraph1: 'RIVA yavutse kuri ikibazo cyoroheje ariko cyihariye: ubuzima bwinshi bwarohewe kuri mihanda twese ibyo bishobora kuvurwa nko guhinga uwohe, kubura gusubira imodoka, no kubura amakuru mu gihe cyose.',
      storyParagraph2: 'Tangiye i Rwanda, twabonye ibibazo byose abayobozi, abagiriye imodoka, nubuyobozi babura — kuva imyitwarire yakozwe nukohe kugira ngo guhaze amavuta no kubura imikorere yamasosiyete ya modoka.',
      storyParagraph3: 'Twasaze ikibazo cyihariye:',
      storyParagraph4: '"Niba modoka zishobora kugira, kura ibyago, no kubungabunga ubuzima mu gihe cyose?"',
      storyParagraph5: 'Iyo kibazo cyatumye RIVA — Umufasha wa modoka wihuse kuri mudasobwa wa kuri AI na IoT.',
      storyParagraph6: 'Sisitemu yateguwe sibuza gusubira imodoka ariko kugukumura imyitwarire, gufasha imikorere, no guhindura ubwoko bwo gukoresha imodoka muri Rwanda no hanze.',
      ourMission: 'Intego Zacu',
      missionDescription: 'Gukora mihanda manzira nubwoko bwo kugenda buhoro bikoresha ubufasha bwo kuri mudasobwa wa modoka bwo kura ibyago, gukumura imyitwarire, no gufasha abayobozi, abagiriye imodoka, nubuyobozi nubumenyi mu gihe cyose.',
      ourVision: 'Icyo Tegereje',
      visionDescription: 'Kuba uburyo bwo kugenda buhose bwihuse muri Rwanda no ku isi, aho buri modoka ihujwe, buri nzira ari amanini, nibu gutanga byose bikorwa nubumenyi mu gihe cyose.',
      ourValues: 'Imyitwarire Yacu',
      valuesDescription: 'Ibintu bivugurira ibose twakoze',
      safetyFirst: 'Ubuzima Bwa Mbere',
      safetyFirstDesc: 'Dushyiramo ubuzima hejuru yibindi, dufite ko buri muyobozi asubira ari amanzi.',
      aiInnovation: 'Ishoramari rya AI',
      aiInnovationDesc: 'Gukoresha ubufasha bwo kuri mudasobwa buhuse kugira ngo guhindura imikorere yamasosiyete ya modoka.',
      communityImpact: 'Ingaruka ku muryango',
      communityImpactDesc: 'Gukora mihanda manzira kuri buri wese, imodoka imwe imwe.',
      vehiclesProtected: 'Imodoka Zabitswe',
      accuracyRate: 'Ubwoko bwo kuba neza',
      partnerCompanies: 'Kampuni Zahuze',
      monitoring: 'Gusubira',
      ourTechnology: 'Ikoranabuhanga Ryacu',
      technologyDescription: 'AI buhuse rya kumenya modoka yawe',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Sisitemu yacu ya AI, RIVA SOUL, yiga imyitwarire ya modoka yawe no gutanga ubumenyi bwihuse. Iyasha indimi nyinwi harimo Kinyarwanda, ikabasha abayobozi bose muri Rwanda.',
      realtimeAlcoholDetection: 'Gusubira uwohe mu gihe cyose',
      fuelTheftPrevention: 'Guhaza amavuta',
      predictiveMaintenance: 'Gubungabunga',
      voiceAssistantKinyarwanda: 'Umufasha wuvuga mu Kinyarwanda',
      smartMonitoring: 'Gusubira Buhanze',
      smartMonitoringDesc: 'RIVA ikora ibikorwa byihuse biri muri modoka kugira ngo yakire amakuru mu gihe cyose ku bikorwa, imyitwarire, nimbiri zubuzima. Iyi makuru yakorwa nuburyo bwacu bwo AI kugira ngo yire ibyago, gufasha imikorere, no gutanga ibyabujisha mbere yuko ibibazo biba.',
      realtimeGpsTracking: 'Gusubira GPS mu gihe cyose',
      intelligentFuelUsage: 'Gusubira gukoresha amavuta buhanze',
      sensorBasedDiagnostics: 'Igerageza ryamabara',
      instantSafetyAlerts: 'Ibyabujisha byihuse bya AI',
      ourTeam: 'Itsinda Ryacu',
      teamDescription: 'Abagize intego ku kubungabunga mihanda',
      // Try App Page
      demoMode: 'Iyerekana',
      tryRivaApp: 'Gerageza RIVA',
      tryRivaAppDesc: 'Gerageza RIVA ukoresheje Expo Go - Ongera gushyiramo',
      installExpoGo: 'Shyira Expo Go',
      installExpoGoDesc: 'Shyira Expo Go ukoresheje Play Store',
      openExpoGo: 'Fungura Expo Go',
      openExpoGoDesc: 'Fungura Expo Go kuri mudasobwa yawe',
      scanQrCode: 'Soma QR Code',
      scanQrCodeDesc: 'Soma QR code iri hasi ukoresheje Expo Go',
      startUsing: 'Tangira gukoresha',
      startUsingDesc: 'Tangira gugerageza RIVA',
      scanQrCodeTitle: 'Soma QR Code',
      scanQrCodeInstruction: 'Koresha Expo Go kugira ngo usome iyi QR code',
      qrCodePlaceholder: 'QR code izagaragara hano uhereye kuri Expo yawe',
      getExpoGo: 'Shyira Expo Go kuri Play Store',
      demoInformation: 'Amakuru yiyerekana',
      demoInfoDesc: 'Iyi ni verisiyo yiyerekana ya RIVA ikora kuri Expo Go. Washobora gugerageza ibikorwa byingenzi harimo gusubira mu gihe cyose, ibyabujisha bya AI, no gucunga imodoka zikoresheje Expo Go. Iyi demo itanga ububasha bwo kumenya uburyo bwo gukorana nuburyo bwacu bwo gufasha modoka.',
    },
    french: {
      // Navbar
      home: 'Accueil',
      about: 'À propos',
      features: 'Fonctionnalités',
      howItWorksNav: 'Comment ça marche',
      appNav: 'Application',
      pricing: 'Tarifs',
      contact: 'Contact',
      login: 'Connexion',
      register: 'S\'inscrire',
      // Hero
      heroTitle: 'Véhicules plus intelligents.',
      heroSubtitle: 'Routes plus sûres.',
      heroDescription: 'RIVA est l\'assistant de véhicule intelligent de nouvelle génération qui prévient les accidents, détecte les risques et optimise les performances de flotte en temps réel.',
      getStarted: 'Commencer',
      downloadApp: 'Télécharger l\'application',
      trustedBy: 'Approuvé par plus de 10 000 conducteurs',
      // Features
      aiPowered: 'Intelligence de véhicule alimentée par l\'IA',
      // Download App Page
      aboutThisApp: 'À propos de cette application',
      aboutThisAppDescription: 'RIVA est l\'assistant de véhicule intelligent de nouvelle génération qui prévient les accidents, détecte les risques et optimise les performances de flotte en temps réel. Notre système alimenté par l\'IA surveille en continu la santé du véhicule, le comportement du conducteur et les conditions environnementales pour fournir des alertes de sécurité instantanées et des recommandations de maintenance prédictive.',
      dataSafety: 'Sécurité des données',
      encryptedTransfer: 'Transfert de données crypté',
      encryptedTransferDesc: 'Vos données sont transférées en toute sécurité',
      requestDeletion: 'Vous pouvez demander la suppression des données',
      requestDeletionDesc: 'Envoyez les demandes de suppression au développeur',
      whatsNew: 'Nouveautés',
      appFeatures: 'Fonctionnalités de l\'application',
      realtimeMonitoring: 'Surveillance en temps réel',
      safetyAlerts: 'Alertes de sécurité',
      fleetManagement: 'Gestion de flotte',
      predictiveMaintenance: 'Maintenance prédictive',
      developerContact: 'Contact développeur',
      email: 'E-mail',
      phone: 'Téléphone',
      website: 'Site web',
      backToHome: 'Retour à l\'accueil',
      install: 'Installer',
      reviews: 'avis',
      downloads: 'téléchargements',
      ratedFor: 'Classé pour',
      updatedOn: 'Mis à jour le',
      // Footer
      rightsReserved: 'Tous droits réservés',
      followUs: 'Suivez-nous',
      quickLinks: 'Liens rapides',
      company: 'Entreprise',
      // Features Section
      featuresTitle: 'Fonctionnalités puissantes',
      featuresSubtitle: 'Tout ce dont vous avez besoin pour gérer votre flotte efficacement',
      accidentPrevention: 'Prévention des accidents',
      accidentPreventionDesc: 'Système alimenté par l\'IA qui détecte et prévient les accidents avant qu\'ils ne se produisent',
      fuelMonitoring: 'Surveillance du carburant',
      fuelMonitoringDesc: 'Suivi du carburant en temps réel pour prévenir le vol et optimiser l\'utilisation',
      gpsTracking: 'Suivi GPS',
      gpsTrackingDesc: 'Surveillance de la position des véhicules 24/7 et capacités de géofencing',
      // How It Works
      howItWorks: 'Comment ça marche',
      howItWorksSubtitle: 'Étapes simples pour commencer avec RIVA',
      step1: 'S\'inscrire',
      step1Desc: 'Créez votre compte en quelques minutes',
      step2: 'Installer l\'application',
      step2Desc: 'Téléchargez et installez l\'application RIVA',
      step3: 'Connecter les véhicules',
      step3Desc: 'Ajoutez vos véhicules au système',
      step4: 'Commencer la surveillance',
      step4Desc: 'Commencez la surveillance en temps réel et les alertes de sécurité',
      // Features Component
      coreFeatures: 'Fonctionnalités principales',
      everythingYouNeed: 'Tout ce dont vous avez besoin pour une mobilité intelligente',
      alcoholDetection: 'Détection d\'alcool',
      alcoholDetectionDesc: 'Analyse BAC en temps réel et système de verrouillage moteur',
      fuelMonitoring: 'Surveillance du carburant',
      fuelMonitoringDesc: 'Détection de vol et consommation inhabituelle',
      gpsTracking: 'Suivi GPS',
      gpsTrackingDesc: 'Localisation en direct et surveillance d\'itinéraire',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Assistant vocal en Kinyarwanda',
      kinyarwandaBadge: 'Kinyarwanda',
      fleetManagement: 'Gestion de flotte',
      fleetManagementDesc: 'Gérez un nombre illimité de véhicules',
      // How It Works Component
      simpleSmartConnected: 'Simple. Intelligent. Connecté.',
      installDevice: 'Installer l\'appareil',
      installDeviceDesc: 'Branchez RIVA dans votre véhicule',
      connectApp: 'Connecter l\'application',
      connectAppDesc: 'Associez avec l\'application mobile RIVA',
      monitorAI: 'Surveiller l\'IA',
      monitorAIDesc: 'Obtenez une intelligence en temps réel',
      // CTA Component
      readyToTransform: 'Prêt à transformer votre flotte?',
      joinThousands: 'Rejoignez des milliers de conducteurs qui font confiance à RIVA pour des trajets plus sûrs',
      requestDemo: 'Demander une démo',
      // App Preview Component
      mobileAppPreview: 'Aperçu de l\'application mobile',
      viewAppScreens: 'Voir les écrans de l\'application',
      realImpact: 'Impact réel, résultats réels',
      fewerAccidents: 'Moins d\'accidents',
      drunkDrivingPrevented: 'Conduite en état d\'ivresse prévenue',
      costSavings: 'Économies de coûts',
      fuelTheftEliminated: 'Vol de carburant éliminé',
      fleetEfficiency: 'Efficacité de la flotte',
      vehiclesManaged: 'Véhicules gérés',
      rivaAppScreens: 'Écrans de l\'application RIVA',
      dashboard: 'Tableau de bord',
      realtimeVehicleStats: 'Suivi de véhicule en temps réel',
      aiAssistant: 'Assistant IA',
      rivaSoulVoice: 'Voix RIVA SOUL',
      fuelMonitor: 'Surveillance du carburant',
      fuelTracking: 'Suivi du carburant',
      safetyAlerts: 'Alertes de sécurité',
      instantNotifications: 'Notifications instantanées',
      gpsTrackingApp: 'Suivi GPS',
      liveLocation: 'Position en direct',
      diagnostics: 'Diagnostics',
      vehicleHealth: 'Santé du véhicule',
      driverBehaviorAnalysis: 'Analyse du comportement du conducteur',
      fleetManagement: 'Tableau de bord de gestion de flotte',
      // Contact Page
      contactUs: 'Contactez-nous',
      contactDescription: 'Vous avez des questions? Nous aimerions avoir de vos nouvelles. Envoyez-nous un message et nous répondrons dès que possible.',
      sendMessage: 'Envoyez-nous un message',
      fullName: 'Nom complet',
      emailAddress: 'Adresse e-mail',
      phoneNumber: 'Numéro de téléphone',
      subject: 'Sujet',
      message: 'Message',
      sendButton: 'Envoyer le message',
      findUsOnSocial: 'Trouvez-nous sur les réseaux sociaux',
      socialDescription: 'Restez connecté avec nous sur les réseaux sociaux pour les mises à jour, les nouvelles et les conseils sur la sécurité routière.',
      visitOurOffice: 'Visitez notre bureau',
      visitOfficeDesc: 'Venez nous rendre visite à notre siège à Kigali, Rwanda',
      howCanWeHelp: 'Comment pouvons-nous vous aider?',
      tellUsMore: 'Dites-nous en plus sur votre demande...',
      // About Page
      aboutRiva: 'À propos de RIVA',
      aboutDescription: 'RIVA est un assistant de véhicule intelligent de nouvelle génération qui prévient les accidents, détecte les risques et optimise les performances de flotte en temps réel. Nous avons pour mission de rendre les routes plus sûres pour tous.',
      ourStory: 'Notre histoire',
      storyParagraph1: 'RIVA est né d\'un problème simple mais urgent: trop de vies sont perdues sur nos routes en raison de causes évitables comme la conduite en état d\'ivresse, une mauvaise surveillance des véhicules et un manque de données en temps réel.',
      storyParagraph2: 'En partant du Rwanda, nous avons vu les défis quotidiens auxquels sont confrontés les conducteurs, les propriétaires de flottes et les gouvernements — des accidents causés par l\'alcool au vol de carburant et à une gestion inefficace des flottes.',
      storyParagraph3: 'Nous avons posé une question audacieuse:',
      storyParagraph4: '"Et si les véhicules pouvaient penser, détecter les risques et protéger des vies en temps réel?"',
      storyParagraph5: 'Cette question a conduit à RIVA — un assistant de véhicule intelligent en temps réel alimenté par l\'IA et l\'IoT.',
      storyParagraph6: 'Un système conçu non seulement pour surveiller les véhicules, mais pour prévenir activement les accidents, améliorer l\'efficacité et transformer la mobilité au Rwanda et au-delà.',
      ourMission: 'Notre mission',
      missionDescription: 'Rendre les routes plus sûres et les transports plus intelligents en utilisant l\'intelligence de véhicule alimentée par l\'IA qui détecte les risques, prévient les accidents et donne aux conducteurs, aux propriétaires de flottes et aux gouvernements des informations en temps réel.',
      ourVision: 'Notre vision',
      visionDescription: 'Devenir la plateforme de mobilité intelligente leader au Rwanda et dans le monde, où chaque véhicule est connecté, chaque trajet est sûr et chaque décision est alimentée par des données en temps réel.',
      ourValues: 'Nos valeurs',
      valuesDescription: 'Les principes qui guident tout ce que nous faisons',
      safetyFirst: 'Sécurité d\'abord',
      safetyFirstDesc: 'Nous privilégions la sécurité avant tout, garantissant que chaque conducteur rentre chez lui en sécurité.',
      aiInnovation: 'Innovation IA',
      aiInnovationDesc: 'Exploiter l\'intelligence artificielle de pointe pour transformer la gestion de flotte.',
      communityImpact: 'Impact communautaire',
      communityImpactDesc: 'Rendre les routes plus sûres pour tous, un véhicule à la fois.',
      vehiclesProtected: 'Véhicules protégés',
      accuracyRate: 'Taux de précision',
      partnerCompanies: 'Entreprises partenaires',
      monitoring: 'Surveillance',
      ourTechnology: 'Notre technologie',
      technologyDescription: 'IA de pointe qui comprend votre véhicule',
      rivaSoulAI: 'RIVA SOUL AI',
      rivaSoulAIDesc: 'Notre système IA propriétaire, RIVA SOUL, apprend les modèles de votre véhicule et fournit des prédictions intelligentes. Il prend en charge plusieurs langues, y compris le Kinyarwanda, le rendant accessible à tous les conducteurs au Rwanda.',
      realtimeAlcoholDetection: 'Détection d\'alcool en temps réel',
      fuelTheftPrevention: 'Prévention du vol de carburant',
      predictiveMaintenance: 'Maintenance prédictive',
      voiceAssistantKinyarwanda: 'Assistant vocal en Kinyarwanda',
      smartMonitoring: 'Surveillance intelligente',
      smartMonitoringDesc: 'RIVA exploite une technologie de capteur intelligente intégrée dans le véhicule pour capturer des données en temps réel sur les performances, le comportement et les conditions de sécurité. Ces données sont traitées par notre moteur IA pour identifier les risques, optimiser les opérations et fournir des alertes proactives avant que les problèmes ne surviennent.',
      realtimeGpsTracking: 'Suivi GPS en temps réel et géofencing',
      intelligentFuelUsage: 'Surveillance intelligente de la consommation de carburant',
      sensorBasedDiagnostics: 'Diagnostics de véhicule basés sur des capteurs',
      instantSafetyAlerts: 'Alertes de sécurité alimentées par l\'IA instantanées',
      ourTeam: 'Notre équipe',
      teamDescription: 'Experts passionnés dédiés à la sécurité routière',
      // Try App Page
      demoMode: 'Mode démo',
      tryRivaApp: 'Essayer RIVA',
      tryRivaAppDesc: 'Découvrez RIVA avec Expo Go - Aucune installation requise',
      installExpoGo: 'Installer Expo Go',
      installExpoGoDesc: 'Télécharger Expo Go depuis Play Store',
      openExpoGo: 'Ouvrir Expo Go',
      openExpoGoDesc: 'Lancer l\'application Expo Go sur votre appareil',
      scanQrCode: 'Scanner le code QR',
      scanQrCodeDesc: 'Scanner le code QR ci-dessous avec Expo Go',
      startUsing: 'Commencer',
      startUsingDesc: 'Commencer à tester l\'application RIVA',
      scanQrCodeTitle: 'Scanner le code QR',
      scanQrCodeInstruction: 'Utilisez Expo Go pour scanner ce code QR et lancer la démo',
      qrCodePlaceholder: 'Le code QR sera affiché ici depuis votre projet Expo',
      getExpoGo: 'Obtenir Expo Go sur Play Store',
      demoInformation: 'Informations sur la démo',
      demoInfoDesc: 'Ceci est une version de démonstration de l\'application RIVA fonctionnant sur Expo Go. Vous pouvez tester les fonctionnalités principales, notamment la surveillance en temps réel, les alertes alimentées par l\'IA et la gestion de flotte sans installer l\'application complète. La démo offre une expérience pratique de notre technologie d\'assistant de véhicule intelligent.',
    }
  }

  const t = (key) => {
    return translations[language][key] || translations['english'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
